#! /bin/sh

# Limpiar procesos viejos al iniciar bspwm
pkill -x sxhkd 2>/dev/null
pkill -x eww 2>/dev/null

# Arrancar un solo sxhkd normal
sxhkd -c "$HOME/.config/sxhkd/sxhkdrc" >/dev/null 2>&1 &

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
/usr/bin/vmware-user-suid-wrapper &
/usr/bin/dunst &
"$HOME/.config/polybar/launch.sh" &
/usr/local/bin/picom &
xset r rate 300 50
bspc rule -a gnome-calendar state=floating sticky=on center=on
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

if [ -f "$HOME/.cache/current-wallpaper" ]; then
    WALL="$(cat "$HOME/.cache/current-wallpaper")"

    if [ -f "$WALL" ]; then
        feh --bg-fill "$WALL"
    fi
fi
